# Activity 1.02
Create a 1-deimensional tensor with 24 elements

In [1]:
import tensorflow as tf

In [2]:
array1 = tf.Variable([*range(24)])

In [3]:
array1.shape.as_list()

[24]

Create a new matrix with 6 rows and 2 columns by reshaping the matrix

In [4]:
reshape1 = tf.reshape(array1, shape=[12,2])
reshape1

<tf.Tensor: shape=(12, 2), dtype=int32, numpy=
array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]], dtype=int32)>

In [5]:
reshape1.shape.as_list()

[12, 2]

Create a new tensor with shape 3 x 4 x 2 by reshaping the original tensor. Verify by printing the shape and the rank

In [6]:
reshape2 = tf.reshape(array1, shape=[3, 4, 2])
reshape2

<tf.Tensor: shape=(3, 4, 2), dtype=int32, numpy=
array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]], dtype=int32)>

In [7]:
reshape2.shape.as_list()

[3, 4, 2]

In [8]:
tf.rank(reshape2).numpy()

3

## Transposition
Take the transpotion of the first reshaped tensor and print its shape

In [9]:
transpose1 = tf.transpose(reshape1)
transpose1

<tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23]], dtype=int32)>

In [10]:
transpose1.shape.as_list()

[2, 12]