# Exercise 1.05
## Matrix Multiplication

In [1]:
import tensorflow as tf

Create two matrices with 2 rows and 4 columns

In [2]:
matrix1 = tf.Variable([[1,2,3,4], [5,6,7,8]])
matrix1

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>

In [3]:
matrix1.shape.as_list()

[2, 4]

In [4]:
matrix2 = tf.Variable([[3,2,7,2], [6,8,2,4]])
matrix2

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[3, 2, 7, 2],
       [6, 8, 2, 4]], dtype=int32)>

In [5]:
matrix2.shape.as_list()

[2, 4]

Reshape `matrix2` so that it has 4 rows and 2 columns then multiply `matrix1` and the reshaped `matrix2` together with `matrix1` first

In [6]:
matmul1 = tf.matmul(matrix1, tf.reshape(matrix2, [4,2]))
matmul1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 43,  46],
       [115, 110]], dtype=int32)>

In [7]:
matmul1.shape.as_list()

[2, 2]

Reshape `matrix1` so that it has 4 rows and 2 columns then multiply the reshaped `matrix1` and `matrix2` together with `matrix2` last

In [8]:
matmul2 = tf.matmul(tf.reshape(matrix1, [4, 2]), matrix2)
matmul2

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[15, 18, 11, 10],
       [33, 38, 29, 22],
       [51, 58, 47, 34],
       [69, 78, 65, 46]], dtype=int32)>

In [9]:
matmul2.shape.as_list()

[4, 4]

Transpose `matrix1` then multiply the transposed `matrix1` and `matrix2` together with `matrix2` last

In [10]:
matmul3 = tf.matmul(matrix1, matrix2, transpose_a=True)
matmul3

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[33, 42, 17, 22],
       [42, 52, 26, 28],
       [51, 62, 35, 34],
       [60, 72, 44, 40]], dtype=int32)>

Transpose `matrix2` then multiply `matrix1` and the transposed `matrix2` together with `matrix1` first using the `@` operator

In [12]:
matrix1 @ tf.transpose(matrix2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 36,  44],
       [ 92, 124]], dtype=int32)>