# Exercise 1.05: Performing Tensor Multiplication in TensorFlow

In [1]:
import tensorflow as tf

In [2]:
matrix1 = tf.Variable([[1.0,0.0,3.0,1.0,2.0], \
                       [0.0,1.0,1.0,1.0,1.0], \
                       [2.0,1.0,0.0,2.0,0.0]], \
                      tf.float32)
matrix1

<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[1., 0., 3., 1., 2.],
       [0., 1., 1., 1., 1.],
       [2., 1., 0., 2., 0.]], dtype=float32)>

In [3]:
matrix1.shape.as_list()

[3, 5]

In [4]:
matrix2 = tf.Variable([[0.49], \
                       [0.18], \
                       [0.24], \
                       [1.02], \
                       [0.68]])
matrix2

<tf.Variable 'Variable:0' shape=(5, 1) dtype=float32, numpy=
array([[0.49],
       [0.18],
       [0.24],
       [1.02],
       [0.68]], dtype=float32)>

In [6]:
matmul1 = tf.matmul(matrix1, matrix2)
matmul1

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[3.5900002],
       [2.1200001],
       [3.2      ]], dtype=float32)>