# Activity1.01

Scalar and vector addition

## Scalar Addition
Create 2 scalar variables and add them together

In [1]:
import tensorflow as tf

In [2]:
var1 = tf.Variable(26, tf.int32)
var1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=26>

In [3]:
var2 = tf.Variable(16, tf.int32)
var2

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=16>

In [4]:
var_sum = var1+var2
var_sum.numpy()

42

## Vector and Scalar Addition
Add a scalar to a vector

In [5]:
scalar1 = tf.Variable(26.2, tf.float32)
scalar1

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=26.2>

In [6]:
vector1 = tf.Variable([7.2, 1.1], tf.float32)
vector1

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([7.2, 1.1], dtype=float32)>

In [7]:
vector_scalar_sum = scalar1 + vector1
vector_scalar_sum.numpy()

array([33.4     , 27.300001], dtype=float32)

## Matrix Addition
Create two 3x3 matrices and add them together

In [8]:
matrix1 = tf.Variable([[10, -21, 18], [12, 28, -9], [-2, 20, 8]], tf.int32)
matrix1

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[ 10, -21,  18],
       [ 12,  28,  -9],
       [ -2,  20,   8]], dtype=int32)>

In [9]:
matrix2 = tf.Variable([[-2, 17, 2], [0, 12, 7], [10, 10, -4]], tf.int32)
matrix2

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[-2, 17,  2],
       [ 0, 12,  7],
       [10, 10, -4]], dtype=int32)>

In [10]:
matrix_sum = matrix1 + matrix2
matrix_sum.numpy()

array([[ 8, -4, 20],
       [12, 40, -2],
       [ 8, 30,  4]], dtype=int32)