# Activity1.01

In this activity we will perform tensor addition with scalars, vectors, and matrices.

Throughout the activity we will use the example of votes cast for polictal candidates from different districts across different political parties.

## Scalar Addition

Create 2 scalar variables to represent the number of votes cast for a particular candidate in different districts

In [1]:
import tensorflow as tf

In [2]:
var1 = tf.Variable(2706, tf.int32)
var1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2706>

In [3]:
var2 = tf.Variable(2386, tf.int32)
var2

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2386>

In [4]:
var_sum = var1 + var2
var_sum.numpy()

5092

## Vector and Scalar Addition

Each of the political candiates from one district recieved 100 mail-in votes, calculate the new total number of votes for each candidate. Create a vector representing the number of votes for each candidate and a scalar representing the mail-in votes.

In [5]:
scalar1 = tf.Variable(100, tf.int32)
scalar1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=100>

In [6]:
vector1 = tf.Variable([4113, 7511, 6259], tf.int32)
vector1

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4113, 7511, 6259], dtype=int32)>

In [7]:
vector_scalar_sum = scalar1 + vector1
vector_scalar_sum.numpy()

array([4213, 7611, 6359], dtype=int32)

## Matrix Addition
Create three 2x3 matrices representing the votes for each candidate and district.

In [8]:
matrix1 = tf.Variable([[4113, 7511, 6259], [3870, 6725, 6962]], tf.int32)
matrix1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[4113, 7511, 6259],
       [3870, 6725, 6962]], dtype=int32)>

In [9]:
matrix2 = tf.Variable([[5102, 7038, 6591], [3661, 5901, 6235]], tf.int32)
matrix3 = tf.Variable([[951, 1208, 1098], [870, 645, 948]], tf.int32)

Add together the votes from the matrices to total the number of votes for each district across candidates

In [10]:
matrix_sum = matrix1 + matrix2 + matrix3
matrix_sum.numpy()

array([[10166, 15757, 13948],
       [ 8401, 13271, 14145]], dtype=int32)