# Activity 1.03

Throughout the activity you will run through many of the concepts learned in Chapter 1.

In [1]:
import tensorflow as tf

Create a 3x4 tensor as an input in which the rows represent the sales from various sales representatives, the columns represent various vehicles available at the dealership, and values represent the average percentage difference from MSRP. The values can be positive or negative depending on whether the salesperson was able to sell for more or less than the MSRP.

In [2]:
input1 = tf.Variable([[-0.013, 0.024, 0.06, 0.022], 
                       [0.001, -0.047, 0.039, 0.016],
                       [0.018, 0.030, -0.021, -0.028]], tf.float32)
input1

2021-09-09 15:19:17.195007: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-0.013,  0.024,  0.06 ,  0.022],
       [ 0.001, -0.047,  0.039,  0.016],
       [ 0.018,  0.03 , -0.021, -0.028]], dtype=float32)>

Create a 4x1 weights tensor with shape 4x1 representing the MSRP of the cars

In [7]:
weights = tf.Variable([[19995.95], [24995.50], [36745.50], [29995.95]], tf.float32)
weights

<tf.Variable 'Variable:0' shape=(4, 1) dtype=float32, numpy=
array([[19995.95],
       [24995.5 ],
       [36745.5 ],
       [29995.95]], dtype=float32)>

Create bias tensor of size 3x1 representing the fixed costs associated with each salesperson

In [4]:
bias = tf.Variable([[-2500.0],[-2500.0],[-2500.0]], tf.float32)
bias

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-2500.],
       [-2500.],
       [-2500.]], dtype=float32)>

Matrix multiply the input with the weight to show the average deviation from MSRP on all cars and add the bias to subtract the fixed costs of the salesperson.

In [5]:
output = tf.matmul(input1,weights) + bias
output

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[  704.52246],
       [-1741.794  ],
       [-3001.728  ]], dtype=float32)>

Apply a relu activation function to the highlight the net-positive salespeople

In [6]:
output = tf.keras.activations.relu(output)
output

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[704.52246],
       [  0.     ],
       [  0.     ]], dtype=float32)>