# Activity 1.03
## Matrix Multiplication

Create 2 3 x 3 matrices and matrix multiply the first by the second

In [0]:
import tensorflow as tf

In [3]:
matrix1 = tf.Variable([[1,2,3], [4,5,6], [7,8,9]])
matrix1

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [4]:
matrix2 = tf.Variable([[6,2,6], [-2,4,0], [-4,2,-8]])
matrix2

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[ 6,  2,  6],
       [-2,  4,  0],
       [-4,  2, -8]], dtype=int32)>

In [5]:
matmul1 = tf.matmul(matrix1, matrix2)
matmul1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[-10,  16, -18],
       [-10,  40, -24],
       [-10,  64, -30]], dtype=int32)>

Create 2 tensors with shape 3 x 2 x 2

In [0]:
tensor1 = tf.Variable([[[2,1], [2, 1]], [[2,1],[2,1]], [[2,1],[2,1]]])
tensor2 = tf.Variable([[[-3,7], [4, 5]], [[-10,2],[-3,3]], [[2,2],[0,-1]]])


Matrix multiply the two tensors together

In [10]:
matmul2 = tf.matmul(tensor1, tensor2)
matmul2

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ -2,  19],
        [ -2,  19]],

       [[-23,   7],
        [-23,   7]],

       [[  4,   3],
        [  4,   3]]], dtype=int32)>

In [11]:
matmul2.shape.as_list()

[3, 2, 2]