# Activity 1.03: Applying Activation Functions 

In [1]:
import tensorflow as tf

In [3]:
input1 = tf.Variable([[-0.013, 0.024, 0.06, 0.022], \
                       [0.001, -0.047, 0.039, 0.016],\
                       [0.018, 0.030, -0.021, -0.028]],\
                     tf.float32)

In [4]:
weights = tf.Variable([[19995.95], [24995.50], [36745.50], \
                       [29995.95]], tf.float32)
weights

<tf.Variable 'Variable:0' shape=(4, 1) dtype=float32, numpy=
array([[19995.95],
       [24995.5 ],
       [36745.5 ],
       [29995.95]], dtype=float32)>

In [5]:
bias = tf.Variable([[-2500.0],[-2500.0],[-2500.0]], \
                   tf.float32)
bias

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-2500.],
       [-2500.],
       [-2500.]], dtype=float32)>

In [6]:
output = tf.matmul(input1,weights) + bias
output

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[  704.58545],
       [-1741.7827 ],
       [-3001.75   ]], dtype=float32)>

In [7]:
output = tf.keras.activations.relu(output)
output

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[704.58545],
       [  0.     ],
       [  0.     ]], dtype=float32)>