# Activity 1.03
## Matrix Multiplication

In [2]:
import tensorflow as tf

Create a matrix to represent a car sales record for 9-person sales team in which the rows represent each member of the sales team and each column represents the number of sales of each of the 10 cars on offer

In [3]:
sales_record = tf.Variable([[1,0,0,0,1,1,1,2,0,1], [0,2,3,2,0,1,1,2,2,1], [0,0,0,0,0,1,0,0,0,1],
                            [1,4,2,1,1,1,0,0,3,1], [2,2,2,1,1,1,1,0,0,1], [1,0,0,1,1,1,0,0,0,1],
                            [2,1,1,2,1,2,1,0,2,0], [2,2,2,1,1,1,1,0,0,1], [3,2,4,3,1,3,5,1,3,4]], dtype=tf.float32)
sales_record

<tf.Variable 'Variable:0' shape=(9, 10) dtype=float32, numpy=
array([[1., 0., 0., 0., 1., 1., 1., 2., 0., 1.],
       [0., 2., 3., 2., 0., 1., 1., 2., 2., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 4., 2., 1., 1., 1., 0., 0., 3., 1.],
       [2., 2., 2., 1., 1., 1., 1., 0., 0., 1.],
       [1., 0., 0., 1., 1., 1., 0., 0., 0., 1.],
       [2., 1., 1., 2., 1., 2., 1., 0., 2., 0.],
       [2., 2., 2., 1., 1., 1., 1., 0., 0., 1.],
       [3., 2., 4., 3., 1., 3., 5., 1., 3., 4.]], dtype=float32)>

Create a matrix to represent a sales price of each of the 10 cars

In [9]:
prices = tf.Variable([[19995,9995,7995,11495,12095,24995,10745,14995,9995,8745]],dtype=tf.float32)
prices

<tf.Variable 'Variable:0' shape=(1, 10) dtype=float32, numpy=
array([[19995.,  9995.,  7995., 11495., 12095., 24995., 10745., 14995.,
         9995.,  8745.]], dtype=float32)>

In [11]:
sales_numbers = tf.matmul(sales_record, prices, transpose_b=True)
sales_numbers

<tf.Tensor: shape=(9, 1), dtype=float32, numpy=
array([[106565.],
       [161430.],
       [ 33740.],
       [163280.],
       [144045.],
       [ 77325.],
       [173790.],
       [144045.],
       [367205.]], dtype=float32)>

Create a tensor that represents the inventory of the cars in different stores in different regions. The first dimension will be the region and there are 3 regions, the second dimension will be the stores and there are 6 stores per region, and there are 10 brands of cars.

In [12]:
inventory = tf.Variable([[[11,2,3,2,5,2,4,8,10,3], [1,2,1,1,0,0,1,1,1,2], [9,12,8,2,4,2,4,5,13,9],
                        [0,2,2,1,2,3,0,2,1,3], [6,7,5,5,5,3,9,8,1,9], [5,7,4,3,8,12,7,8,10,7]],
                       [[13,12,13,22,25,21,24,18,15,13], [9,21,18,20,15,21,14,9,11,3], [1,0,1,2,2,3,2,3,0,3],
                        [21,17,17,16,14,23,24,28,30,23], [16,15,19,21,14,12,18,15,10,22], [17,14,11,9,10,20,16,18,15,13]],
                       [[0,0,0,1,0,2,5,2,1,3], [9,5,6,4,7,8,4,3,0,3], [14,21,13,20,18,12,9,18,14,11],
                        [6,3,6,8,6,8,5,4,10,4], [1,2,1,1,1,0,1,3,2,3], [10,8,6,9,11,13,10,8,10,7]]], dtype=tf.float32)


Matrix multiply the inventory tensors with the cost per car to determine the value of the inventory at each store

In [14]:
inventory_cost = tf.matmul(inventory, prices, transpose_b=True)
inventory_cost

<tf.Tensor: shape=(3, 6, 1), dtype=float32, numpy=
array([[[ 686500.],
        [ 112700.],
        [ 811810.],
        [ 212870.],
        [ 728210.],
        [ 989445.]],

       [[2355370.],
        [1891545.],
        [ 242865.],
        [2832585.],
        [2043090.],
        [1997535.]],

       [[ 181430.],
        [ 722705.],
        [1944050.],
        [ 811050.],
        [ 173525.],
        [1277890.]]], dtype=float32)>

In [16]:
inventory_cost.shape.as_list()

[3, 6, 1]