# Exercise 1.02

In this exercise we will create scalars, vectors, matrices, and tensors in TensorFlow.

Throughout the exercise we will use the example of votes cast for political candidates from different districts across different political parties.

## Scalars

In [1]:
import tensorflow as tf

Let's create a scalar to represent the number of votes cast for a particular candidate

In [2]:
int_variable = tf.Variable(4113, tf.int16)
int_variable

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=4113>

In [3]:
tf.rank(int_variable)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

Display the rank as number

In [4]:
tf.rank(int_variable).numpy()

0

In [5]:
int_variable.shape

TensorShape([])

Display the shape as list

In [6]:
int_variable.shape.as_list()

[]

## Vectors

Let's create a vector of floats to represent the proportion of votes cast 3 different particular candidate

In [7]:
vector_variable = tf.Variable([0.23, 0.42, 0.35], tf.float32)
vector_variable

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([0.23, 0.42, 0.35], dtype=float32)>

In [8]:
tf.rank(vector_variable).numpy()

1

In [9]:
vector_variable.shape.as_list()

[3]

## Matrices

Let's create a matrix to represent the votes cast for 3 different particular candidate in two different districts. This matrix will have 3 columns representing the candidates and two rows representing the districts.

In [10]:
matrix_variable = tf.Variable([[4113, 7511, 6259], [3870, 6725, 6962]], tf.int32)
matrix_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[4113, 7511, 6259],
       [3870, 6725, 6962]], dtype=int32)>

In [11]:
tf.rank(matrix_variable).numpy()

2

In [12]:
matrix_variable.shape.as_list()

[2, 3]

## Tensors
Let's create a tensor to represent the votes cast for 3 different particular candidate in two different districts, for 3 political parties. This tensor will have 3 dimensions, the first representing the candidates, the second representing the districts, and the third representing the political party.

In [13]:
tensor_variable = tf.Variable([[[4113, 7511, 6259], [3870, 6725, 6962]],
                               [[5102, 7038, 6591], [3661, 5901, 6235]],
                               [[951, 1208, 1098], [870, 645, 948]]])
tensor_variable

<tf.Variable 'Variable:0' shape=(3, 2, 3) dtype=int32, numpy=
array([[[4113, 7511, 6259],
        [3870, 6725, 6962]],

       [[5102, 7038, 6591],
        [3661, 5901, 6235]],

       [[ 951, 1208, 1098],
        [ 870,  645,  948]]], dtype=int32)>

In [14]:
tf.rank(tensor_variable).numpy()

3

In [15]:
tensor_variable.shape.as_list()

[3, 2, 3]