# Exercise 4.01

In [1]:
import tensorflow as tf
from tensorflow.python.framework import random_seed
random_seed.set_seed(42)

In [2]:
model = tf.keras.Sequential()

In [3]:
model.add(tf.keras.layers.InputLayer(input_shape=(8,), name='Input_layer'))
model.add(tf.keras.layers.Dense(4, activation='relu', name='Hidden_layer'))
model.add(tf.keras.layers.Dense(1, name='Output_layer'))

In [4]:
model.variables

[<tf.Variable 'Hidden_layer/kernel:0' shape=(8, 4) dtype=float32, numpy=
 array([[ 0.23272598, -0.08342904, -0.20805556, -0.05022925],
        [-0.65950376,  0.26116616,  0.33957738,  0.52671605],
        [-0.387033  , -0.39145875, -0.26815173,  0.3144303 ],
        [-0.5187517 ,  0.0679726 ,  0.1055128 ,  0.5652378 ],
        [-0.69372314,  0.03002477,  0.19027466, -0.425214  ],
        [ 0.32445234,  0.06481981, -0.5549861 ,  0.2499001 ],
        [ 0.2266649 , -0.23058692,  0.14342624, -0.40923697],
        [ 0.49884576, -0.08397353,  0.63431376, -0.37119436]],
       dtype=float32)>,
 <tf.Variable 'Hidden_layer/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'Output_layer/kernel:0' shape=(4, 1) dtype=float32, numpy=
 array([[ 0.4116491 ],
        [-0.03400517],
        [ 0.94426155],
        [-0.5429311 ]], dtype=float32)>,
 <tf.Variable 'Output_layer/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [5]:
data = tf.random.normal((32,8))

In [6]:
prediction = model.predict(data)
prediction

array([[ 1.3631216 ],
       [ 0.        ],
       [ 1.2020777 ],
       [ 1.6465328 ],
       [ 1.0614607 ],
       [ 0.        ],
       [ 0.56806594],
       [ 1.3524766 ],
       [ 0.48797646],
       [ 2.2744834 ],
       [-0.00594931],
       [ 1.6033156 ],
       [ 2.4203465 ],
       [-0.7845831 ],
       [ 0.        ],
       [-0.01533174],
       [-0.11469087],
       [ 0.40171936],
       [ 0.15567245],
       [-0.6729224 ],
       [ 0.30236   ],
       [ 1.1654029 ],
       [-0.51089466],
       [ 1.4327216 ],
       [ 0.1439977 ],
       [ 1.0886748 ],
       [-1.2347256 ],
       [ 1.3302152 ],
       [-0.13363513],
       [ 0.10070556],
       [-0.8036719 ],
       [-0.92067367]], dtype=float32)