# Exercise 1.04: Performing Tensor Reshaping and Transposition in TensorFlow

In [1]:
import tensorflow as tf

In [2]:
matrix1 = tf.Variable([[1,2,3,4], [5,6,7,8]])

In [3]:
matrix1.shape.as_list()

[2, 4]

Reshape to have 4 rows and 2 columns

In [4]:
reshape1 = tf.reshape(matrix1, shape=[4,2])
reshape1

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])>

In [5]:
reshape1.shape.as_list()

[4, 2]

Reshape to have 1 row and 8 columns

In [6]:
reshape2 = tf.reshape(matrix1, shape=[1,8])
reshape2

<tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6, 7, 8]])>

In [7]:
reshape2.shape.as_list()

[1, 8]

Reshape to have 8 rows and 1 column

In [8]:
reshape3 = tf.reshape(matrix1, shape=[8,1])
reshape3

<tf.Tensor: shape=(8, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])>

In [9]:
reshape3.shape.as_list()

[8, 1]

Reshape to have shape (2x2x2)

In [10]:
reshape4 = tf.reshape(matrix1, shape=[2,2,2])
reshape4

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])>

In [11]:
reshape4.shape.as_list()

[2, 2, 2]

In [12]:
tf.rank(reshape4).numpy()

3

## Transposition

In [13]:
transpose1 = tf.transpose(matrix1)
transpose1

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])>

Verify that transposition and reshaping are different

In [14]:
transpose1 == reshape1

<tf.Tensor: shape=(4, 2), dtype=bool, numpy=
array([[ True, False],
       [False, False],
       [False, False],
       [False,  True]])>

Transpose the tensor named `reshape4`

In [15]:
transpose2 = tf.transpose(reshape4)
transpose2

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])>