# Exercise 1.03

In this exercise we will perform tensor addition with scalars, vectors, and matrices.

Throughout the exercise we will use the example of votes cast for political candidates from different districts across different political parties.

## Scalar Addition

In [5]:
import tensorflow as tf

Let's create scalars to represent the number of votes cast for a particular candidate in different districts

In [6]:
int1 = tf.Variable(4113, tf.int32)
int2 = tf.Variable(3870, tf.int32)

Let's add the votes for the candidate across districts

In [9]:
int_sum = int1+int2
int_sum

<tf.Tensor: shape=(), dtype=int32, numpy=7983>

In [10]:
int_sum.numpy()

7983

## Vector Addition

Let's create vectors to represent the number of votes cast for 3 candidates in different districts

In [11]:
vec1 = tf.Variable([4113, 7511, 6259], tf.int32)
vec2 = tf.Variable([3870, 6725, 6962], tf.int32)

Let's add the votes for each candidate across districts

In [12]:
vec_sum = vec1 + vec2

In [11]:
vec_sum.numpy()

array([ 7983, 14236, 13221], dtype=int32)

In [12]:
print((vec1[0] + vec2[0]).numpy())
print((vec1[1] + vec2[1]).numpy())
print((vec1[2] + vec2[2]).numpy())

7983
14236
13221


## Matrix Addition

Let's create matrices to represent the number of votes cast for 3 candidates in different districts for each political party

In [14]:
matrix1 = tf.Variable([[4113, 7511, 6259], [5102, 7038, 6591]], tf.int32)
matrix2 = tf.Variable([[3870, 6725, 6962], [3661, 5901, 6235]], tf.int32)
matrix3 = tf.Variable([[951, 1208, 1098], [870, 645, 948]], tf.int32)

In [15]:
matrix1.shape == matrix2.shape == matrix3.shape

True

In [16]:
matrix_sum = matrix1 + matrix2 + matrix3
matrix_sum.numpy()

array([[ 8934, 15444, 14319],
       [ 9633, 13584, 13774]], dtype=int32)

In [17]:
print((matrix1[0][0] + matrix2[0][0] + matrix3[0][0]).numpy())
print((matrix1[0][1] + matrix2[0][1] + matrix3[0][1]).numpy())
print((matrix1[0][2] + matrix2[0][2] + matrix3[0][2]).numpy())
print((matrix1[1][0] + matrix2[1][0] + matrix3[1][0]).numpy())
print((matrix1[1][1] + matrix2[1][1] + matrix3[1][1]).numpy())
print((matrix1[1][2] + matrix2[1][2] + matrix3[1][2]).numpy())

8934
15444
14319
9633
13584
13774
