# Exercise 2.04: Loading Text Data for TensorFlow Models

In [1]:
import tensorflow as tf

In [2]:
df = tf.data.experimental.make_csv_dataset\
     ('../Datasets/drugsComTrain_raw.tsv', \
      batch_size=1, field_delim='\t')

In [3]:
def prep_ds(ds, shuffle_buffer_size=1024, batch_size=32):
    # Shuffle the dataset
    ds = ds.shuffle(buffer_size=shuffle_buffer_size)
    # Repeat the dataset
    ds = ds.repeat()
    # Batch the dataset
    ds = ds.batch(batch_size)

    return ds

In [4]:
ds = prep_ds(df, batch_size=5)

In [5]:
for x in ds.take(1):
    print(x)

OrderedDict([('', <tf.Tensor: shape=(5, 1), dtype=int32, numpy=
array([[193905],
       [ 91684],
       [ 38033],
       [108776],
       [ 84770]])>), ('drugName', <tf.Tensor: shape=(5, 1), dtype=string, numpy=
array([[b'Dilaudid'],
       [b'Protonix IV'],
       [b'Adipex-P'],
       [b'Nexplanon'],
       [b'Ethinyl estradiol / norgestimate']], dtype=object)>), ('condition', <tf.Tensor: shape=(5, 1), dtype=string, numpy=
array([[b'Pain'],
       [b"Barrett's Esophagus"],
       [b'Weight Loss'],
       [b'Birth Control'],
       [b'Birth Control']], dtype=object)>), ('review', <tf.Tensor: shape=(5, 1), dtype=string, numpy=
array([[b'"I have been given Dilaudid through an IV on several occasions and on all those occasions I&#039;d rather just dealt with the pain. Today the hospital gave me Dilaudid, and some nausea medication... On ever occasion that I have been given Dilaudid through IV instantly my head gets too heavy, I begin to get dizzy and lighthead. I always get VERY NAUSEOU

In [6]:
import tensorflow_hub as hub
embedding = "https://tfhub.dev/google/tf2-preview"\
            "/gnews-swivel-20dim/1"
hub_layer = hub.KerasLayer(embedding, input_shape=[], \
                           dtype=tf.string, trainable=True)

In [7]:
for x in ds.take(1):
    print(hub_layer(tf.reshape(x['review'],[-1])))

tf.Tensor(
[[ 0.85637194 -1.506148    2.0898294   0.76287127 -1.3294315  -3.2016342
  -1.5625719   2.5138297   1.9493035  -0.87237185 -0.71198505  1.2482367
   0.8347453   0.74195063 -3.2654202   1.7437259   3.6106536  -2.433589
  -2.1442554  -1.8830311 ]
 [ 1.3633374  -3.472839    1.6306508   1.3522071  -3.7051663  -5.591705
  -2.5833106   1.9622269   2.148968   -0.5469887  -1.8512614   3.1438973
  -0.81081367  0.9246471  -6.089089    2.6840522   5.7409143  -4.6783543
  -3.0686712  -1.891416  ]
 [-0.38192645 -3.241573    1.20132     0.37701157 -3.3210232  -3.9527822
  -3.1954875   1.5348208   2.1768715   1.4031676  -3.039334    1.8451444
   1.5885328   0.62233907 -4.6009307   3.2810917   2.9764225  -2.7709908
  -1.3856741  -0.16450648]
 [ 1.3386972  -4.202724    2.456265    1.6445506  -4.9147415  -4.971446
  -3.1711445   1.771192    3.425477    0.30268404 -2.1084783   2.555107
   0.74540186  0.77879316 -5.8247786   3.1800213   5.0734744  -2.6060858
  -2.3680193  -1.4511749 ]
 [ 1.1435