# Exercise 2.04

In [1]:
import tensorflow as tf
from tensorflow.python.framework import random_seed
random_seed.set_seed(42)

In [2]:
df = tf.data.experimental.make_csv_dataset('../Datasets/drugsComTrain_raw.tsv', batch_size=1, field_delim='\t')

In [3]:
def prep_ds(ds, shuffle_buffer_size=1024, batch_size=32):
    # Shuffle the dataset
    ds = ds.shuffle(buffer_size=shuffle_buffer_size)
    # Repeat the dataset
    ds = ds.repeat()
    # Batch the dataset
    ds = ds.batch(batch_size)
    
    return ds

In [4]:
ds = prep_ds(df, batch_size=5)

Take 1 batch and print it out

In [5]:
for x in ds.take(1):
    print(x)

OrderedDict([('', <tf.Tensor: shape=(5, 1), dtype=int32, numpy=
array([[ 94649],
       [150691],
       [  7340],
       [200310],
       [ 16372]], dtype=int32)>), ('drugName', <tf.Tensor: shape=(5, 1), dtype=string, numpy=
array([[b'Abilify'],
       [b'Sulfamethoxazole / trimethoprim'],
       [b'Monistat 7-Day Combination Pack'],
       [b'Varenicline'],
       [b'Ethinyl estradiol / norethindrone']], dtype=object)>), ('condition', <tf.Tensor: shape=(5, 1), dtype=string, numpy=
array([[b'Depression'],
       [b'Acne'],
       [b'Vaginal Yeast Infection'],
       [b'Smoking Cessation'],
       [b'Birth Control']], dtype=object)>), ('review', <tf.Tensor: shape=(5, 1), dtype=string, numpy=
array([[b'"On 2 mg. It made me feel empty inside. Like things didn&#039;t bring excitement, adrenaline. Everything seemed blank. Had major sweet cravings for the first month or two but it leveled off. The most sweet cravings were at 5 mg a day. Really brought reality into full focus. Got it a pharm

Obtain pre-trained text embedding model from TesorFlow hub

In [6]:
import tensorflow_hub as hub
embedding = "https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1"
hub_layer = hub.KerasLayer(embedding, input_shape=[], 
                           dtype=tf.string, trainable=True)

In [7]:
for x in ds.take(1):
    print(hub_layer(tf.reshape(x['review'],[-1])))

tf.Tensor(
[[ 0.5140007  -2.0179267   1.38361     1.476341   -1.6306221  -3.778787
  -3.089537    1.2128762   2.5229087   0.12723097 -3.4533403   2.6671464
  -0.2185451   0.07074512 -4.3222446   2.5112097   3.0222752  -3.332357
  -2.653579   -0.50742686]
 [ 1.8564253  -2.6656833   2.7356663   1.5028186  -2.4612641  -4.6607885
  -1.9340665   2.34501     2.513298   -0.10728899 -0.6880438   2.1895087
  -0.06693801  0.7737151  -5.3564095   2.3556361   5.413457   -2.8227847
  -1.3990408  -1.0817306 ]
 [-0.91448885 -1.1078665  -0.9016515   0.20297056 -0.15448709 -2.034957
  -1.3925421  -0.19757764  0.39035913 -0.18046005 -1.3317407   1.9738865
  -0.17704543 -0.22645436 -2.3172152   2.7074795  -0.0819451  -2.2373881
  -1.1885055   0.4849162 ]
 [ 1.5079169  -3.5022748   1.5204316   0.76069295 -4.1588597  -5.5369263
  -3.7877033   1.3243417   2.812435   -0.3422503  -2.5983195   2.7843983
   1.2904108   1.4363046  -6.169245    1.9605458   5.8139772  -3.706125
  -1.9065906  -2.252074  ]
 [-0.0702